name: Deploy Spring Boot API - Java 21

on:
  push:
    branches: [main, v3]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/gestorcanaapi-deploy:latest ./gestorcana-api

      - name: Login Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gestorcanaapi-deploy:latest

      - name: Deploy no Oracle Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/gestorcanaapi-deploy:latest
            docker stop gestorcanaapi-deploy-container || true
            docker rm gestorcanaapi-deploy-container || true
            docker run -d --restart=always --name gestorcanaapi-deploy-container -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/gestorcanaapi-deploy:latest
